### ISSUE TITLE
Is there any plan to open source the pre-training code?

### ISSUE THREAD

**Issue by Meron-TANG** [evo-design/protein-dpo#3]
Hi there, 

This is a great piece of work. Are there any plans to open source the training scripts in the future?

Jianx

**Comment by twidatalla** [comment]
Hi Jianx,

Yes there is! Not sure when we will get around to this but sometime soon.

Best,
Talal

**Comment by Meron-TANG** [comment]
Thanks！

**Comment by XiaoNan1111** [comment]
Hi @twidatalla, just wanted to follow up on this. Is there any update on the timeline for releasing the training scripts? I'm very interested in this work. Thanks!
