### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by TangYiChing** [evo-design/protein-dpo#4]
Could you update the environment file?

Here is the error message from the code: `$conda env create -f environment.yml`

> Pip subprocess error:
ERROR: Ignored the following versions that require a different python version: 0.41.0 Requires-Python >=3.10; 0.41.1 **Requires-Python >=3.10**; 2.6.0 Requires-Python <4,>=3.10; 2.6.1 Requires-Python <4,>=3.10; 2.6.2 Requires-Python <4,>=3.10; 2.7.0 Requires-Python <4,>=3.10; 3.0.0b1 Requires-Python >=3.10
ERROR: Could not find a version that satisfies the requirement fair-esm==2.0.1 (from versions: 0.1.0, 0.1.1, 0.2.0, 0.3.0, 0.3.1, 0.4.0, 0.4.2, 0.5.0, 1.0.0, 1.0.2, 1.0.3, 2.0.0)
ERROR: No matching distribution found for fair-esm==2.0.1

**Comment by twidatalla** [comment]
Hi @TangYiChing 

Thanks for reporting this issue. I believe this is happening because Python=3.10 is not specified in the environment.yml file. Can you try adding it to the dependencies like this (on line 10 of environment.yml)?

dependencies:
  - python=3.10
  
Let me know if this fixes the issue, if so I will push the change to the repo.
  
Best,
Talal

**Comment by TangYiChing** [comment]
you have many dependencies are for python3.9:

dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - aiohttp=3.9.0=py39h5eee18b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - argcomplete=1.12.3=pyhd3eb1b0_0
  - aria2=1.36.0=h1e4e653_3
  - async-timeout=4.0.3=py39h06a4308_0
  - attrs=23.1.0=py39h06a4308_0

**Comment by twidatalla** [comment]
Hi @TangYiChing,

Sometimes Conda can resolve these by installing versions of the package compatible with Python3.10. Does the installation work when you add in python=3.10 as a dependency?

Best,
Talal

**Comment by TangYiChing** [comment]
> Hi @TangYiChing,
> 
> Sometimes Conda can resolve these by installing versions of the package compatible with Python3.10. Does the installation work when you add in python=3.10 as a dependency?
> 
> Best, Talal

No, it didn't work. **- fair-esm==2.0.1** complains version not found, so I have to remove the version in order to install esm (i.e., -fair-esm)

**Comment by twidatalla** [comment]
Ah okay, maybe uninstall -fair-esm and instead:

pip install git+https://github.com/facebookresearch/esm.git

Looking at the other issue you raised, maybe the version of fair-esm installed is not up to date.

**Comment by twidatalla** [comment]
Going to close this issue as running:

`pip install git+https://github.com/facebookresearch/esm.git`

solves the issue as per this [comment](https://github.com/evo-design/protein-dpo/issues/2#issuecomment-2204118911)
