### ISSUE TITLE
example csv file for running score.py

### ISSUE THREAD

**Issue by TangYiChing** [evo-design/protein-dpo#5]
Hi,

Could you provide some examples for this column value?

`<feature> : Scalar label of the feature for optimization`

**Comment by tonytu16** [comment]
Following up on this, I wonder if the authors can also provide some example files for running scoring? I am trying to reproduce the results reported in the paper but not sure how I should pre-process the S669 dataset. Thank you!

**Comment by twidatalla** [comment]
Hi @TangYiChing an example for this value is the experimental ddG of each mutation to compare with the models predictions. 

@tonytu16 I've added the fireprot_homologue_free.csv as an example

**Comment by TangYiChing** [comment]
> Hi @TangYiChing an example for this value is the experimental ddG of each mutation to compare with the models predictions.
> 
> @tonytu16 I've added the fireprot_homologue_free.csv as an example

Thank you, Talla, for clarification.
