### ISSUE TITLE
buggy fixed_pos sampling

### ISSUE THREAD

**Issue by adrienchaton** [evo-design/protein-dpo#6]
Hi and thanks for sharing your work

I saw in the other issues that someone pointed to the formatting issues with some parenthesis issues in the argument parser.
Besides that, here fixed is not defined https://github.com/evo-design/protein-dpo/blob/main/sample.py#L15

I would imagine you wanted to do something like
```
for fixed_idx in [int(pos) for pos in args.fixed_pos.split(",")]:
```
and specify --fixed_pos 1,2,3,4 (whatsoever, 1-indexed and comma separated for example)

**Comment by twidatalla** [comment]
Hi @adrienchaton, thanks for catching this! Just made the fix in the most recent commit. Let me know if it doesn't work.
